version: "3"

dotenv:
  - .env

includes:
  diff-engine:
    taskfile: workspaces/diff-engine/Taskfile.yml
  ui:
    taskfile: workspaces/ui/Taskfile.yml
    dir: workspaces/ui

tasks:
  workspaces:setup:
    env:
      OPTIC_SKIP_PREBUILT_INSTALLS: "true"
    cmds:
      - yarn install

  workspaces:build:
    desc: Build Yarn workspaces
    deps: ["workspaces:setup"]
    cmds:
      - yarn wsrun --stages --report --fast-exit --exclude-missing ws:build
    sources:
      - !workspaces/*/build/**/*
    generates:
      - workspaces/diff-engine-wasm/lib/**/*
      - workspaces/diff-engine-wasm/engine/browser/**/*
      - workspaces/diff-engine-wasm/engine/build/**/*
      # - workspace/diff-engine-wasm/engine/target/**/* # do we need this?
      - workspaces/*/build/**/*

  workspaces:clean:
    desc: Remove previous build artifacts
    cmds:
      - yarn wsrun --stages --report --fast-exit ws:clean

  spec:build:
    dir: workspaces/ui
    env:
      PUBLIC_URL: "https://apidocs.o3c.info"
      CI: "false"
    cmds:
      - yarn build-spec

  npm:publish:
    deps:
      - workspaces:build
    env:
      OPTIC_SKIP_PREBUILT_INSTALLS: "false"
    cmds:
      - yarn install

  flush-to-disk:
    cmds:
      - sudo /usr/sbin/purge
    status:
      - uname -a | grep -qv Darwin


