storage: ../storage

packages:
  '@useoptic/*':
      access: $all
      publish: $all
      proxy: npmjs
  '*/*':
      access: $all
      proxy: npmjs
  '**':
      access: $all
      proxy: npmjs
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
logs:
  - {type: stdout, format: pretty-timestamped, level: debug}

max_body_size: 1024mb
