name: Matrix build with Task
on:
  push:
    branches:
      - taskfile2
jobs:
  build_rust_binaries:
    strategy:
      matrix:
        platform:
          - os: windows-latest
            task: diff-engine:build-windows
          - os: ubuntu-latest
            task: diff-engine:build-linux
          - os: macos-latest
            task: diff-engine:build-macos
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Install Task
        uses: Arduino/actions/setup-taskfile@9d04a51fc17daddb0eb127933aaa950af1e3ff97 # they dont give us any tags :\
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable
          profile: minimal
          override: true
      - run: task diff-engine:add-targets
      - run: task ${{ matrix.platform.task }}
      - run: task flush-to-disk
      - run: task diff-engine:locate-binaries
