version: 3

vars:
  DRY_RUN: '{{default "true" .DRY_RUN}}'
  TIMESTAMP: $(date +%s)

tasks:
  run:
    desc: Build a side-channel release for @useoptic/cli and publish it to s3
    vars:
      # get the local-cli version and strip anything after a hyphen, "0.0.0-blah" to "0.0.0"
      BASE_VERSION: $(cat workspaces/local-cli/package.json | jq -r .version | awk -F'-' '{print $1}')
      VERSION_TAG: "{{default .TIMESTAMP .VERSION_TAG}}"
      VERSION: "{{.BASE_VERSION}}-alpha.{{.VERSION_TAG}}" # https://www.youtube.com/watch?v=Ct6BUPvE2sM
      TMP_DIR: /tmp/{{.TIMESTAMP}}
      BUCKET: '{{default "optic-side-channel-staging" .SIDE_CHANNEL_BUCKET}}'
      FLAGS_FILE: '{{.FLAGS_FILE}}'
    deps:
      - task: :workspaces:build
        env:
          FLAGS_FILE: '{{.FLAGS_FILE}}'
      - :verdaccio:up
    cmds:
      - rm -rf {{.TMP_DIR}} && mkdir -p {{.TMP_DIR}}
      - task: publish-local
        vars:
          BUCKET: "{{.BUCKET}}"
          VERSION: "{{.VERSION}}"
      - task: save-packages-to-disk
        vars:
          PACKAGES:
            sh: node workspaces/scripts/list-workspace-packages.js | sed "s/,/ /g"
          VERSION: "{{.VERSION}}"
          TMP_DIR: "{{.TMP_DIR}}"
      - task: upload-to-s3
        vars:
          BUCKET: "{{.BUCKET}}"
          VERSION: "{{.VERSION}}"
          TGZ_DIR: "{{.TMP_DIR}}"
      - task: :release:announce
        vars:
          MESSAGE: "New CLI build: https://{{.BUCKET}}.s3.amazonaws.com/{{.VERSION}}/cli-{{.VERSION}}.tgz"
      - task: outputs
        vars:
          VERSION: "{{.VERSION}}"

  upload-to-s3:
    cmds:
      - |
        if [ "{{.DRY_RUN}}" = "true" ]
        then
          aws s3 sync {{.TGZ_DIR}} s3://{{.BUCKET}}/{{.VERSION}}/ --include=*.tgz --delete --dryrun
        else
          aws s3 sync {{.TGZ_DIR}} s3://{{.BUCKET}}/{{.VERSION}}/ --include=*.tgz --delete --sse=AES256
        fi

  upload-diff-engine-to-s3:
    vars:
      BUCKET: '{{default "optic-side-channel-staging" .BUCKET}}'
      VERSION: '{{.VERSION}}'
    # ➜ aws s3 ls s3://optic-packages/dists/optic_diff/v9.0.11/
    # 2021-02-17 10:47:14    1918033 optic_diff-v9.0.11-linux.tar.gz
    # 2021-02-17 10:47:15     997647 optic_diff-v9.0.11-macos-aarch64.tar.gz
    # 2021-02-17 10:47:14     997932 optic_diff-v9.0.11-macos.tar.gz
    # 2021-02-17 10:47:15     869189 optic_diff-v9.0.11-win64.tar.gz
    cmds:
      # kind of a hack job. but it mimics the existing tags we're appending to the binary tarballs
      # in the main release flow. the resulting tarballs will be in ./buid/dist
      - |
        for binary in $(task diff-engine:locate-binaries)
        do
          if [[ $binary =~ "x86_64-apple" ]]; then
            tag="macos"
          elif [[ $binary =~ "aarch64-apple" ]]; then
            tag="macos-aarch64"
          elif [[ $binary =~ "windows" ]]; then
            tag="win64"
          elif [[ $binary =~ "linux" ]]; then
            tag="linux"
          else
            echo "Could not identify the arch for file: $binary"
            exit 1
          fi
          filename="optic_diff-v{{.VERSION}}-$tag"
          chmod +x $binary
          mkdir -p build/$filename build/dist
          cp $binary build/$filename/
          tar -C build -czvf build/dist/${filename}.tar.gz $filename
        done
      - ls -lh build/dist

  # write values to share outside task
  outputs:
    cmds:
      - mkdir -p /tmp/outputs
      - echo "{{.VERSION}}" > /tmp/outputs/release-version.txt

  bump-version:
    env:
      S3_HTTPS_URL: "{{.S3_HTTPS_URL}}"
      VERSION: "{{.VERSION}}"
    cmds:
      - node workspaces/scripts/use-s3-dependencies.js

  save-packages-to-disk:
    vars:
      NPM_REGISTRY: '{{default "http://0.0.0.0:4873" .NPM_REGISTRY}}'
    cmds:
      - |
        for pkg in {{.PACKAGES}}
        do
          url="{{.NPM_REGISTRY}}/@useoptic%2f${pkg}/-/${pkg}-{{.VERSION}}.tgz"
          wget -nv $url -P {{.TMP_DIR}}
        done

  publish-local:
    env:
      OPTIC_PUBLISH_SCOPE: private
    cmds:
      - task: bump-version
        vars:
          S3_HTTPS_URL: https://{{.BUCKET}}.s3.amazonaws.com
          VERSION: "{{.VERSION}}"
      - node workspaces/scripts/publish.js
      - task: reset-working-tree

  # reset working tree because package.json's and README.md's were updated with `yarn bump`
  reset-working-tree:
    - |
      if uname -a | grep -q Darwin
      then
        files=$(find -E workspaces/ -depth 2 -type f -regex ".*(package.json|README.md)")
        echo $files | xargs git checkout
      fi
